zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301

spring:
  application:
    name: api-gateway
server:
  port: 8080
